### Part-1 [PANDAS BASIC]

In [ ]:
# 1. Import Pandas using the alias pd.
import pandas as pd

In [ ]:
data = {
    "Employee_ID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010,
                    1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020],

    "Name": ["Aarav Sharma", "Priya Singh", "Rahul Verma", "Ananya Patel", "Vikram Joshi",
             "Neha Gupta", "Rohan Mehta", "Isha Kapoor", "Karan Malhotra", "Meera Shah",
             "Aditya Rao", "Sneha Jain", "Arjun Nair", "Kavya Mishra", "Manish Yadav",
             "Pooja Agarwal", "Sahil Khan", "Riya Das", "Mohit Soni", "Tanya Roy"],

    "Age": [25, 28, 30, 24, 32, 27, 29, 26, 35, 31, 23, 28, 33, 26, 37, 29, 24, 32, 27, 30],

    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male",
               "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female",
               "Male", "Female"],

    "Department": ["IT", "HR", "Finance", "IT", "Sales", "IT", "HR", "Marketing", "Finance",
                    "IT", "Sales", "Marketing", "IT", "HR", "Finance", "Sales", "Marketing",
                    "IT", "Sales", "Finance"],

    "City": ["Indore", "Bhopal", "Indore", "Pune", "Mumbai", "Indore", "Delhi", "Pune", "Mumbai",
             "Bhopal", "Indore", "Delhi", "Pune", "Bhopal", "Delhi", "Mumbai", "Indore", "Delhi",
             "Pune", "Bhopal"],

    "Experience": [2, 5, 7, 1, 8, 4, 6, 3, 10, 7, 1, 5, 9, 3, 12, 6, 2, 8, 4, 7],

    "Salary": [45000, 55000, 72000, 40000, 68000, 62000, 58000, 50000, 90000, 78000,
               38000, 61000, 85000, 48000, 98000, 64000, 43000, 82000, 52000, 76000],

    "Performance_Score": [78, 85, 88, 72, 76, 91, 69, 82, 94, 89, 65, 87, 93, 75, 90, 81, 70, 95, 74, 86],

    "Attendance": [92, 95, 89, 90, 84, 97, 78, 93, 91, 96, 74, 88, 94, 86, 87, 90, 82, 98, 85, 93],

    "Projects": [3, 4, 5, 2, 6, 5, 3, 4, 7, 6, 2, 5, 7, 3, 8, 5, 3, 7, 4, 6],

    "Status": ["Active", "Active", "Active", "Active", "Active", "Active", "Inactive",
               "Active", "Active", "Active", "Inactive", "Active", "Active", "Active",
               "Active", "Active", "Active", "Active", "Active", "Active"]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df.to_csv("employee_management.csv", index=False)

In [ ]:
# 2. Read the CSV file into a DataFrame
df = pd.read_csv("employee_management.csv")

In [ ]:
#3.. Display the complete DataFrame.
print(df)

    Employee_ID            Name  Age  Gender Department    City  Experience  \
0          1001    Aarav Sharma   25    Male         IT  Indore           2
1          1002     Priya Singh   28  Female         HR  Bhopal           5
2          1003     Rahul Verma   30    Male    Finance  Indore           7
3          1004    Ananya Patel   24  Female         IT    Pune           1
4          1005    Vikram Joshi   32    Male      Sales  Mumbai           8
5          1006      Neha Gupta   27  Female         IT  Indore           4
6          1007     Rohan Mehta   29    Male         HR   Delhi           6
7          1008     Isha Kapoor   26  Female  Marketing    Pune           3
8          1009  Karan Malhotra   35    Male    Finance  Mumbai          10
9          1010      Meera Shah   31  Female         IT  Bhopal           7
10         1011      Aditya Rao   23    Male      Sales  Indore           1
11         1012      Sneha Jain   28  Female  Marketing   Delhi           5
12         1013      Arjun Nair   33    Male         IT    Pune           9
13         1014    Kavya Mishra   26  Female         HR  Bhopal           3
14         1015    Manish Yadav   37    Male    Finance   Delhi          12
15         1016   Pooja Agarwal   29  Female      Sales  Mumbai           6
16         1017      Sahil Khan   24    Male  Marketing  Indore           2
17         1018        Riya Das   32  Female         IT   Delhi           8
18         1019      Mohit Soni   27    Male      Sales    Pune           4
19         1020       Tanya Roy   30  Female    Finance  Bhopal           7

    Salary  Performance_Score  Attendance  Projects    Status
0    45000                 78          92         3    Active
1    55000                 85          95         4    Active
2    72000                 88          89         5    Active
3    40000                 72          90         2    Active
4    68000                 76          84         6    Active
5    62000                 91          97         5    Active
6    58000                 69          78         3  Inactive
7    50000                 82          93         4    Active
8    90000                 94          91         7    Active
9    78000                 89          96         6    Active
10   38000                 65          74         2  Inactive
11   61000                 87          88         5    Active
12   85000                 93          94         7    Active
13   48000                 75          86         3    Active
14   98000                 90          87         8    Active
15   64000                 81          90         5    Active
16   43000                 70          82         3    Active
17   82000                 95          98         7    Active
18   52000                 74          85         4    Active
19   76000                 86          93         6    Active

In [ ]:
#4.Display the first 5 records using head().
df.head(5)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active

In [ ]:
# 5.Display the last 5 records using tail()
df.tail(5)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

In [ ]:
#6.Find the number of rows and columns.
df.shape

(20, 12)

In [ ]:
# 7. Display all column names.
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'Department', 'City',
       'Experience', 'Salary', 'Performance_Score', 'Attendance', 'Projects',
       'Status'],
      dtype='object')

In [ ]:
# 8. Use info() to inspect the dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        20 non-null     int64
 1   Name               20 non-null     object
 2   Age                20 non-null     int64
 3   Gender             20 non-null     object
 4   Department         20 non-null     object
 5   City               20 non-null     object
 6   Experience         20 non-null     int64
 7   Salary             20 non-null     int64
 8   Performance_Score  20 non-null     int64
 9   Attendance         20 non-null     int64
 10  Projects           20 non-null     int64
 11  Status             20 non-null     object
dtypes: int64(7), object(5)
memory usage: 2.0+ KB

In [ ]:
# 9. Generate a statistical summary of the numerical columns.
df.dtypes

Employee_ID           int64
Name                 object
Age                   int64
Gender               object
Department           object
City                 object
Experience            int64
Salary                int64
Performance_Score     int64
Attendance            int64
Projects              int64
Status               object
dtype: object

## Part - 2 [SELECTING DATA]

In [ ]:
# 1. Display only the Name, Department, Salary, and Status columns.
df[["Name","Department","Salary","Status"]]

              Name Department  Salary    Status
0     Aarav Sharma         IT   45000    Active
1      Priya Singh         HR   55000    Active
2      Rahul Verma    Finance   72000    Active
3     Ananya Patel         IT   40000    Active
4     Vikram Joshi      Sales   68000    Active
5       Neha Gupta         IT   62000    Active
6      Rohan Mehta         HR   58000  Inactive
7      Isha Kapoor  Marketing   50000    Active
8   Karan Malhotra    Finance   90000    Active
9       Meera Shah         IT   78000    Active
10      Aditya Rao      Sales   38000  Inactive
11      Sneha Jain  Marketing   61000    Active
12      Arjun Nair         IT   85000    Active
13    Kavya Mishra         HR   48000    Active
14    Manish Yadav    Finance   98000    Active
15   Pooja Agarwal      Sales   64000    Active
16      Sahil Khan  Marketing   43000    Active
17        Riya Das         IT   82000    Active
18      Mohit Soni      Sales   52000    Active
19       Tanya Roy    Finance   76000    Active

In [ ]:
# 2. Display only Name, Experience, and Performance_Score
df[["Name","Experience","Performance_Score"]]

              Name  Experience  Performance_Score
0     Aarav Sharma           2                 78
1      Priya Singh           5                 85
2      Rahul Verma           7                 88
3     Ananya Patel           1                 72
4     Vikram Joshi           8                 76
5       Neha Gupta           4                 91
6      Rohan Mehta           6                 69
7      Isha Kapoor           3                 82
8   Karan Malhotra          10                 94
9       Meera Shah           7                 89
10      Aditya Rao           1                 65
11      Sneha Jain           5                 87
12      Arjun Nair           9                 93
13    Kavya Mishra           3                 75
14    Manish Yadav          12                 90
15   Pooja Agarwal           6                 81
16      Sahil Khan           2                 70
17        Riya Das           8                 95
18      Mohit Soni           4                 74
19       Tanya Roy           7                 86

In [ ]:
# 3. Display the first 10 rows.
df.head(10)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active

In [ ]:
# 4. Using loc[], display rows from index 5 to 10
df.loc[5:10]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive

In [ ]:
# 5. Using iloc[], display the first 5 rows and first 6 columns.
df.iloc[0:5,0:6]

   Employee_ID          Name  Age  Gender Department    City
0         1001  Aarav Sharma   25    Male         IT  Indore
1         1002   Priya Singh   28  Female         HR  Bhopal
2         1003   Rahul Verma   30    Male    Finance  Indore
3         1004  Ananya Patel   24  Female         IT    Pune
4         1005  Vikram Joshi   32    Male      Sales  Mumbai

In [ ]:
# 6. Select the Salary column and inspect its values.
df["Salary"]

0     45000
1     55000
2     72000
3     40000
4     68000
5     62000
6     58000
7     50000
8     90000
9     78000
10    38000
11    61000
12    85000
13    48000
14    98000
15    64000
16    43000
17    82000
18    52000
19    76000
Name: Salary, dtype: int64

### Part - 3 [BASIC ANALYSIS]

In [ ]:
# 1. Find the average employee salary.
df["Salary"].mean()

np.float64(63250.0)

In [ ]:
# 2. Find the maximum salary.
df["Salary"].max()

98000

In [ ]:
# 3. Find the minimum salary.
df["Salary"].min()

38000

In [ ]:
# 4. Find the average age of employees.
df["Age"].mean()

np.float64(28.8)

In [ ]:
# 5. Find the average experience.
df["Experience"].mean()

np.float64(5.5)

In [ ]:
# 6. Find the average performance score.
df["Performance_Score"].mean()

np.float64(82.0)

In [ ]:
# 7.. Find the highest attendance percentage.
df["Attendance"].max()

98

In [ ]:
# 8. Find the total number of projects completed by all employees.
df["Projects"].sum()

np.int64(95)

### Part - 4  [FILTERING]

In [ ]:
# 1. Display employees from the IT department.
df[df["Department"] == "IT"]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active

In [ ]:
# 2. Display employees who work in Indore.
df[df["City"] == "Indore"]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active

In [ ]:
# 3.Display employees with salary greater than 60000.
df[df["Salary"] > 60000]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

In [ ]:
# 4. Display employees with experience greater than 5 years
df[df["Experience"] > 5]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

In [ ]:
#5. Display employees whose performance score is greater than 85.
df[df["Performance_Score"] > 85]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status,Annual_Salary,Performance_Level,Experience_Level,Attendance_Status
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active,864000,Good,mid-Level,low
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active,744000,Exellent,Junior,Good
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active,1080000,Exellent,Senior,Good
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active,936000,Good,mid-Level,Good
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active,732000,Good,mid-Level,low
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active,1020000,Exellent,Senior,Good
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active,1176000,Exellent,Senior,low
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active,984000,Exellent,Senior,Good
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active,912000,Good,mid-Level,Good

In [ ]:
# 6. Display employees whose attendance is below 85.
df[df["Attendance"] < 85]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active

In [ ]:
# 7. Display all female employees.
df[df["Gender"] == "Female"]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
13,1014,Kavya Mishra,26,Female,HR,Bhopal,3,48000,75,86,3,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

In [ ]:
# 8. Display all inactive employees.
df[df["Status"] == "Inactive"]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive

###Part - 5  [MULTIPLE  CONDITION]

In [ ]:
#1. Find employees from IT with salary greater than 60000.
df[(df["Department"] == "IT") & (df["Salary"] > 60000)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active

In [ ]:
#2. Find employees with experience greater than 5 years AND performance score greater than 85.
df[(df["Experience"] > 5) & (df["Performance_Score"] > 85)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

In [ ]:
#3. Find employees whose salary is greater than 70000 OR performance score is greater than 90.
df[(df["Salary"] > 70000) | (df["Performance_Score"] > 90)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

In [ ]:
#4. Find employees who are from Indore AND have attendance greater than 90.
df[(df["City"] == "Indore") & (df["Attendance"] > 90)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active

In [ ]:
#5. Find active employees whose performance score is below 75.
df[(df["Status"] == "Active") & (df["Performance_Score"] < 75)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active

In [ ]:
#6. Find employees who have completed at least 5 projects and have attendance above 90.
df[(df["Projects"] >= 5) & (df["Attendance"] > 90)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

### Part - 6 [SORTING]

In [ ]:
#1. Sort employees by salary from highest to lowest.
df.sort_values("Salary",ascending = False)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
13,1014,Kavya Mishra,26,Female,HR,Bhopal,3,48000,75,86,3,Active
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive

In [ ]:
#2. Sort employees by performance score from lowest to highest.
df.sort_values("Performance_Score", ascending = True)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active
13,1014,Kavya Mishra,26,Female,HR,Bhopal,3,48000,75,86,3,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active

In [ ]:
#3. Sort employees by experience in descending order.
df.sort_values("Experience" , ascending = False)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active
13,1014,Kavya Mishra,26,Female,HR,Bhopal,3,48000,75,86,3,Active
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive

In [ ]:
#4. Sort employees by attendance from highest to lowest.
df.sort_values("Attendance" , ascending = False)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
13,1014,Kavya Mishra,26,Female,HR,Bhopal,3,48000,75,86,3,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive

In [ ]:
#5. Sort employees first by Department and then by Salary.
df.sort_values(["Department","Salary"])

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
13,1014,Kavya Mishra,26,Female,HR,Bhopal,3,48000,75,86,3,Active
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active

### Part - 7 [CREATING NEW COLUMNS]

In [ ]:
#1. Create a new column called Annual_Salary from the monthly Salary.
df["Annual_Salary"] = df["Salary"]*12

In [ ]:
#2. Create a new column called Performance_Level based on Performance_Score: 90+ = Excellent, 80–89 = Good, below 80 = Needs Improvement.
df["Performance_Level"] = df["Performance_Score"].apply( lambda x : 'Exellent' if x >=90 else 'Good' if x >80  else 'Needs Improvement')

In [ ]:
#3. Create a new column called Experience_Level: 8+ years = Senior, 4–7 years = Mid-Level, below 4 years =Junior.
df["Experience_Level"] = df["Experience"].apply( lambda x: 'Senior' if x >=8 else 'mid-Level' if x >4 else 'Junior' )

In [ ]:
#4. Create a new column called Attendance_Status: 90+ = Good, below 90 = Low.
df["Attendance_Status"] = df["Attendance"].apply(lambda x: 'Good' if x >= 90 else 'low')

In [ ]:
print(df)

    Employee_ID            Name  Age  Gender Department    City  Experience  \
0          1001    Aarav Sharma   25    Male         IT  Indore           2
1          1002     Priya Singh   28  Female         HR  Bhopal           5
2          1003     Rahul Verma   30    Male    Finance  Indore           7
3          1004    Ananya Patel   24  Female         IT    Pune           1
4          1005    Vikram Joshi   32    Male      Sales  Mumbai           8
5          1006      Neha Gupta   27  Female         IT  Indore           4
6          1007     Rohan Mehta   29    Male         HR   Delhi           6
7          1008     Isha Kapoor   26  Female  Marketing    Pune           3
8          1009  Karan Malhotra   35    Male    Finance  Mumbai          10
9          1010      Meera Shah   31  Female         IT  Bhopal           7
10         1011      Aditya Rao   23    Male      Sales  Indore           1
11         1012      Sneha Jain   28  Female  Marketing   Delhi           5
12         1013      Arjun Nair   33    Male         IT    Pune           9
13         1014    Kavya Mishra   26  Female         HR  Bhopal           3
14         1015    Manish Yadav   37    Male    Finance   Delhi          12
15         1016   Pooja Agarwal   29  Female      Sales  Mumbai           6
16         1017      Sahil Khan   24    Male  Marketing  Indore           2
17         1018        Riya Das   32  Female         IT   Delhi           8
18         1019      Mohit Soni   27    Male      Sales    Pune           4
19         1020       Tanya Roy   30  Female    Finance  Bhopal           7

    Salary  Performance_Score  Attendance  Projects    Status  Annual_Salary  \
0    45000                 78          92         3    Active         540000
1    55000                 85          95         4    Active         660000
2    72000                 88          89         5    Active         864000
3    40000                 72          90         2    Active         480000
4    68000                 76          84         6    Active         816000
5    62000                 91          97         5    Active         744000
6    58000                 69          78         3  Inactive         696000
7    50000                 82          93         4    Active         600000
8    90000                 94          91         7    Active        1080000
9    78000                 89          96         6    Active         936000
10   38000                 65          74         2  Inactive         456000
11   61000                 87          88         5    Active         732000
12   85000                 93          94         7    Active        1020000
13   48000                 75          86         3    Active         576000
14   98000                 90          87         8    Active        1176000
15   64000                 81          90         5    Active         768000
16   43000                 70          82         3    Active         516000
17   82000                 95          98         7    Active         984000
18   52000                 74          85         4    Active         624000
19   76000                 86          93         6    Active         912000

    Performance_Level Experience_Level Attendance_Status
0   Needs Improvement           Junior              Good
1                Good        mid-Level              Good
2                Good        mid-Level               low
3   Needs Improvement           Junior              Good
4   Needs Improvement           Senior               low
5            Exellent           Junior              Good
6   Needs Improvement        mid-Level               low
7                Good           Junior              Good
8            Exellent           Senior              Good
9                Good        mid-Level              Good
10  Needs Improvement           Junior               low
11               Good        mid-Level               low
12           Exellent           Senior              Good
13  Needs Improvement           Junior               low
14           Exellent           Senior               low
15               Good        mid-Level              Good
16  Needs Improvement           Junior               low
17           Exellent           Senior              Good
18  Needs Improvement           Junior               low
19               Good        mid-Level              Good

### Part - 8 [VALUE COUNT AND QNIQUE VALUE]

In [ ]:
#1. Find the number of employees in each department.
df["Department"].value_counts()

Department
IT           6
Finance      4
Sales        4
HR           3
Marketing    3
Name: count, dtype: int64

In [ ]:
#2. Find the number of employees in each city.
df["City"].value_counts()

City
Indore    5
Bhopal    4
Pune      4
Delhi     4
Mumbai    3
Name: count, dtype: int64

In [ ]:
#3. Find the number of male and female employees.
df["Gender"].value_counts()

Gender
Male      10
Female    10
Name: count, dtype: int64

In [ ]:
#4. Find the number of active and inactive employees.
df["Status"].value_counts()

Status
Active      18
Inactive     2
Name: count, dtype: int64

In [ ]:
#5. Find all unique departments.
df["Department"].unique()

array(['IT', 'HR', 'Finance', 'Sales', 'Marketing'], dtype=object)

In [ ]:
#6. Find all unique cities.
df["City"].unique()

array(['Indore', 'Bhopal', 'Pune', 'Mumbai', 'Delhi'], dtype=object)

In [ ]:
#7. Find the number of unique departments.
df["Department"].nunique()

5

###Part - 9 [GROUPBY ANALYSIS]

In [ ]:
#1. Find the average salary for each department.
df.groupby("Department")["Salary"].mean()

Department
Finance      84000.000000
HR           53666.666667
IT           65333.333333
Marketing    51333.333333
Sales        55500.000000
Name: Salary, dtype: float64

In [ ]:
#2. Find the average performance score for each department.
df.groupby("Department")["Performance_Score"].mean()

Department
Finance      89.500000
HR           76.333333
IT           86.333333
Marketing    79.666667
Sales        74.000000
Name: Performance_Score, dtype: float64

In [ ]:
#3. Find the average attendance for each department.
df.groupby("Department")["Attendance"].mean()

Department
Finance      90.000000
HR           86.333333
IT           94.500000
Marketing    87.666667
Sales        83.250000
Name: Attendance, dtype: float64

In [ ]:
#4. Find the average experience for each department.
df.groupby("Department")["Experience"].mean()

Department
Finance      9.000000
HR           4.666667
IT           5.166667
Marketing    3.333333
Sales        4.750000
Name: Experience, dtype: float64

In [ ]:
#5. Find the number of employees in each department
df.groupby("Department").count()

,Employee_ID,Name,Age,Gender,City,Experience,Salary,Performance_Score,Attendance,Projects,Status,Annual_Salary,Performance_Level,Experience_Level,Attendance_Status
Department,,,,,,,,,,,,,,,
Finance,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
HR,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
IT,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Marketing,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Sales,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4

In [ ]:
#6. Find the average salary for each city.
df.groupby("City")["Salary"].mean()

City
Bhopal    64250.0
Delhi     74750.0
Indore    52000.0
Mumbai    74000.0
Pune      56750.0
Name: Salary, dtype: float64

In [ ]:
#7. Find the average performance score for each gender.
df.groupby("Gender")["Performance_Score"].mean()

Gender
Female    84.3
Male      79.7
Name: Performance_Score, dtype: float64

###Part - 10 [INTERMEDIATE ANALYIS]

In [ ]:
#1. Find the top 5 highest-paid employees.
df.sort_values("Salary",ascending = False).head(5)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status,Annual_Salary,Performance_Level,Experience_Level,Attendance_Status
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active,1176000,Exellent,Senior,low
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active,1080000,Exellent,Senior,Good
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active,1020000,Exellent,Senior,Good
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active,984000,Exellent,Senior,Good
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active,936000,Good,mid-Level,Good

In [ ]:
#2. Find the top 5 employees based on performance score.
df.sort_values("Performance_Score" , ascending = False).head(5)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status,Annual_Salary,Performance_Level,Experience_Level,Attendance_Status
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active,984000,Exellent,Senior,Good
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active,1080000,Exellent,Senior,Good
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active,1020000,Exellent,Senior,Good
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active,744000,Exellent,Junior,Good
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active,1176000,Exellent,Senior,low

In [ ]:
#3. Find the 5 employees with the lowest performance score.
df.sort_values("Performance_Score",ascending = True).head(5)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status,Annual_Salary,Performance_Level,Experience_Level,Attendance_Status
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive,456000,Needs Improvement,Junior,low
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive,696000,Needs Improvement,mid-Level,low
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active,516000,Needs Improvement,Junior,low
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active,480000,Needs Improvement,Junior,Good
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active,624000,Needs Improvement,Junior,low

In [ ]:
#4. Find the employee with the highest salary.
df.sort_values("Salary",ascending = False).head(1)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active

In [ ]:
#5. Find the employee with the highest performance score.
df.sort_values("Performance_Score",ascending = False).head(1)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status,Annual_Salary,Performance_Level,Experience_Level,Attendance_Status
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active,984000,Exellent,Senior,Good

In [ ]:
#6. Find the employee with the highest experience.
df.sort_values("Experience",ascending = False).head(1)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status,Annual_Salary,Performance_Level,Experience_Level,Attendance_Status
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active,1176000,Exellent,Senior,low

In [ ]:
df["Salary"].mean()

np.float64(63250.0)

In [ ]:
#7. Find employees whose salary is above the overall average salary.
df[df["Salary"] > df["Salary"].mean()]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status,Annual_Salary,Performance_Level,Experience_Level,Attendance_Status
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active,864000,Good,mid-Level,low
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active,816000,Needs Improvement,Senior,low
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active,1080000,Exellent,Senior,Good
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active,936000,Good,mid-Level,Good
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active,1020000,Exellent,Senior,Good
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active,1176000,Exellent,Senior,low
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active,768000,Good,mid-Level,Good
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active,984000,Exellent,Senior,Good
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active,912000,Good,mid-Level,Good

In [ ]:
df["Performance_Score"].mean()

np.float64(82.0)

In [ ]:
#8. Find employees whose performance score is above the overall average performance score.
df[df["Performance_Score"] > df["Performance_Score"].mean()]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status,Annual_Salary,Performance_Level,Experience_Level,Attendance_Status
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active,660000,Good,mid-Level,Good
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active,864000,Good,mid-Level,low
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active,744000,Exellent,Junior,Good
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active,1080000,Exellent,Senior,Good
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active,936000,Good,mid-Level,Good
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active,732000,Good,mid-Level,low
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active,1020000,Exellent,Senior,Good
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active,1176000,Exellent,Senior,low
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active,984000,Exellent,Senior,Good
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active,912000,Good,mid-Level,Good

###Part - 11 [HR INSIGHTS]

In [ ]:
#1. Identify employees who may need performance improvement. Use performance score below 75.
df[df["Performance_Score"] < 75]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status,Annual_Salary,Performance_Level,Experience_Level,Attendance_Status
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active,480000,Needs Improvement,Junior,Good
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive,696000,Needs Improvement,mid-Level,low
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive,456000,Needs Improvement,Junior,low
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active,516000,Needs Improvement,Junior,low
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active,624000,Needs Improvement,Junior,low

In [ ]:
#2. Identify employees who may have attendance issues. Use attendance below 85.
df[df["Attendance"] < 85]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status,Annual_Salary,Performance_Level,Experience_Level,Attendance_Status
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active,816000,Needs Improvement,Senior,low
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive,696000,Needs Improvement,mid-Level,low
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive,456000,Needs Improvement,Junior,low
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active,516000,Needs Improvement,Junior,low

In [ ]:
#3. Find employees who have high experience (5+ years) but salary below 60000.
df[(df["Experience"] > 5) & (df["Salary"] < 60000)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status,Annual_Salary,Performance_Level,Experience_Level,Attendance_Status
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive,696000,Needs Improvement,mid-Level,low

In [ ]:
#4. Find employees who have high performance (85+) but attendance below 90.
df[(df["Performance_Score"] >=85 ) & (df["Attendance"] <90 )]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status,Annual_Salary,Performance_Level,Experience_Level,Attendance_Status
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active,864000,Good,mid-Level,low
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active,732000,Good,mid-Level,low
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active,1176000,Exellent,Senior,low

In [ ]:
#5. Compare IT, HR, Finance, Sales, and Marketing based on average salary.
df.groupby("Department")["Salary"].mean()

Department
Finance      84000.000000
HR           53666.666667
IT           65333.333333
Marketing    51333.333333
Sales        55500.000000
Name: Salary, dtype: float64

In [ ]:
#6. Compare departments based on average performance score.
df.groupby("Department")["Performance_Score"].mean()

Department
Finance      89.500000
HR           76.333333
IT           86.333333
Marketing    79.666667
Sales        74.000000
Name: Performance_Score, dtype: float64

In [ ]:
#7. Find the department with the highest average salary.
df.groupby("Department")["Salary"].max().head(1)

Department
Finance    98000
Name: Salary, dtype: int64

In [ ]:
#8. Find the department with the highest average performance score.
df.groupby("Department")["Performance_Score"].mean().head(1)

Department
Finance    89.5
Name: Performance_Score, dtype: float64

In [ ]:
print(df)

    Employee_ID            Name  Age  Gender Department    City  Experience  \
0          1001    Aarav Sharma   25    Male         IT  Indore           2
1          1002     Priya Singh   28  Female         HR  Bhopal           5
2          1003     Rahul Verma   30    Male    Finance  Indore           7
3          1004    Ananya Patel   24  Female         IT    Pune           1
4          1005    Vikram Joshi   32    Male      Sales  Mumbai           8
5          1006      Neha Gupta   27  Female         IT  Indore           4
6          1007     Rohan Mehta   29    Male         HR   Delhi           6
7          1008     Isha Kapoor   26  Female  Marketing    Pune           3
8          1009  Karan Malhotra   35    Male    Finance  Mumbai          10
9          1010      Meera Shah   31  Female         IT  Bhopal           7
10         1011      Aditya Rao   23    Male      Sales  Indore           1
11         1012      Sneha Jain   28  Female  Marketing   Delhi           5
12         1013      Arjun Nair   33    Male         IT    Pune           9
13         1014    Kavya Mishra   26  Female         HR  Bhopal           3
14         1015    Manish Yadav   37    Male    Finance   Delhi          12
15         1016   Pooja Agarwal   29  Female      Sales  Mumbai           6
16         1017      Sahil Khan   24    Male  Marketing  Indore           2
17         1018        Riya Das   32  Female         IT   Delhi           8
18         1019      Mohit Soni   27    Male      Sales    Pune           4
19         1020       Tanya Roy   30  Female    Finance  Bhopal           7

    Salary  Performance_Score  Attendance  Projects    Status  Annual_Salary  \
0    45000                 78          92         3    Active         540000
1    55000                 85          95         4    Active         660000
2    72000                 88          89         5    Active         864000
3    40000                 72          90         2    Active         480000
4    68000                 76          84         6    Active         816000
5    62000                 91          97         5    Active         744000
6    58000                 69          78         3  Inactive         696000
7    50000                 82          93         4    Active         600000
8    90000                 94          91         7    Active        1080000
9    78000                 89          96         6    Active         936000
10   38000                 65          74         2  Inactive         456000
11   61000                 87          88         5    Active         732000
12   85000                 93          94         7    Active        1020000
13   48000                 75          86         3    Active         576000
14   98000                 90          87         8    Active        1176000
15   64000                 81          90         5    Active         768000
16   43000                 70          82         3    Active         516000
17   82000                 95          98         7    Active         984000
18   52000                 74          85         4    Active         624000
19   76000                 86          93         6    Active         912000

    Performance_Level Experience_Level Attendance_Status
0   Needs Improvement           Junior              Good
1                Good        mid-Level              Good
2                Good        mid-Level               low
3   Needs Improvement           Junior              Good
4   Needs Improvement           Senior               low
5            Exellent           Junior              Good
6   Needs Improvement        mid-Level               low
7                Good           Junior              Good
8            Exellent           Senior              Good
9                Good        mid-Level              Good
10  Needs Improvement           Junior               low
11               Good        mid-Level               low
12           Exellent           Senior              Good
13  Needs Improvement           Junior               low
14           Exellent           Senior               low
15               Good        mid-Level              Good
16  Needs Improvement           Junior               low
17           Exellent           Senior              Good
18  Needs Improvement           Junior               low
19               Good        mid-Level              Good

In [ ]:
df.to_csv("employee_management.csv", index=False)